#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JukeApp.Resource", IsApplication=true)]

namespace JukeApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TangoAndCache.Resource.String.library_name = global::JukeApp.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int circle_expand = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int circle_path = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int play_pause = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060007
			public const int black_primary = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int black_secondary = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int jukeapp_accent = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int jukeapp_primary = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int jukeapp_primary_dark = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int jukeapp_primary_less_dark = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int loading_background = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int vector_foreground_color = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int white_primary = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int white_secondary = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int animated_bluetooth_loading = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bluetooth_loading_vector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_pause = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_play = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_play_pause = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_skip_next = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_track = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int light_shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rdio_logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ripple_background = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090005
			public const int albumCover = 2131296261;
			
			// aapt resource value: 0x7f09000a
			public const int avatarIcon = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int avatarImage = 2131296267;
			
			// aapt resource value: 0x7f090012
			public const int container = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int containerFrame = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int explText = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int extraExpl = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int logoImage = 2131296271;
			
			// aapt resource value: 0x7f090001
			public const int participantsFrame = 2131296257;
			
			// aapt resource value: 0x7f090013
			public const int pause_state = 2131296275;
			
			// aapt resource value: 0x7f090008
			public const int playPauseButton = 2131296264;
			
			// aapt resource value: 0x7f090014
			public const int play_state = 2131296276;
			
			// aapt resource value: 0x7f090004
			public const int playerFrame = 2131296260;
			
			// aapt resource value: 0x7f090009
			public const int skipNextButton = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int songArtist = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int songName = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int textView3 = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int toolbar = 2131296256;
			
			// aapt resource value: 0x7f09000d
			public const int trackNumber = 2131296269;
			
			// aapt resource value: 0x7f090003
			public const int userList = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int userName = 2131296268;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int loading_anim_time = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int JukeLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int JukeUserLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoadingScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int pause_vector_path = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int play_vector_path = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int JukeAppTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int JukeAppToolbarTitleAppearance = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
